name: Checks

on: [push]

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@master
        with:
          ruby-version: '2.7'
          bundler-cache: true
      - run: bundle install
      - run: bundle exec rubocop
  rspec:
    name: Rspec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@master
        with:
          ruby-version: '2.7'
          bundler-cache: true
      - run: bundle install
      - run: bundle exec rspec